# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(default='', max_length=255, verbose_name='Local table name (<app_label>;<model__name>)')),
                ('ft_id', models.CharField(default='', max_length=255, verbose_name='Fusiontable table id')),
            ],
        ),
    ]
